
SELECT
    reservations.accept_we_travel_together,
    reservations.ack,
    reservations.active AS active,
    reservations.address_id,
    reservations.adjusted,
    reservations.adult,
    reservations.alipay_provider,
    reservations.arrived,
    reservations.cancel_reason,
    reservations.cancel_url,
    reservations.cancelled_by,
    reservations.cc_provider,
    reservations.channel,
    reservations.charge_amount_type,
    reservations.charge_percent,
    reservations.charge_price,
    reservations.charge_price_v2_cents,
    reservations.charge_type,
    reservations.confirmed_at,
    reservations.confirmed_by,
    reservations.corporate_event_id,
    reservations.created_at AS created_at,
    reservations.created_by,
    reservations.date,
    reservations.deleted_at,
    reservations.delivery_channel_id,
    reservations.delivery_discount_amount_cents,
    reservations.delivery_discount_amount_currency,
    reservations.delivery_fee,
    reservations.delivery_fee_in_baht,
    reservations.delivery_fee_per_km_in_baht,
    reservations.delivery_subsidize_cents,
    reservations.delivery_subsidize_currency,
    reservations.delivery_time,
    reservations.dining_occasion_id,
    reservations.distance_to_restaurant,
    reservations.driver_ack,
    reservations.driver_called,
    reservations.driving_duration,
    reservations.driving_duration_checked,
    reservations.email,
    reservations.end_time,
    reservations.for_locking_system,
    reservations.gb_merchant_id,
    reservations.gcal_id,
    reservations.group_booking,
    reservations.guest_id,
    reservations.id AS id,
    reservations.is_order_now,
    reservations.is_temporary,
    reservations.is_valid_reservation,
    reservations.kids,
    reservations.medium,
    reservations.modified_by,
    reservations.name,
    reservations.new_reservation_id,
    reservations.no_show,
    reservations.note,
    reservations.old_reservation_id,
    reservations.original_delivery_fee,
    reservations.party_size,
    reservations.pay_now,
    reservations.payment_start_from,
    reservations.phone,
    reservations.prefix_number_cc,
    reservations.prepared,
    reservations.promptpay_provider,
    reservations.refund,
    reservations.remindered,
    reservations.reservation_filter,
    reservations.reservation_status,
    reservations.restaurant_id AS restaurant_id,
    reservations.self_pickup_ack,
    reservations.service_type,
    reservations.session_id,
    reservations.shopee_pay_provider,
    reservations.skip_reorder_driver,
    reservations.skip_start_time,
    reservations.special_bonus_id,
    reservations.special_request,
    reservations.start_time,
    reservations.table,
    reservations.time_estimation,
    reservations.total_price,
    reservations.total_price_v2_cents,
    reservations.true_wallet_provider,
    reservations.updated_at,
    reservations.used_voucher_amount_by_hh_cents,
    reservations.used_voucher_amount_by_hh_currency,
    reservations.used_voucher_amount_by_restaurant_cents,
    reservations.used_voucher_amount_by_restaurant_currency,
    reservations.user_id AS user_id,
    reservations.voucher_added_at,
    reservations.voucher_id,
    reservations.waiting_for_pick_up,
    reservations.web_v2_host,
    reservations.wechat_pay_provider,
    formatDateTime(date, '%Y%m') AS period,
    restaurant_translations.name AS restaurant_name,
    replaceOne(package_type, '"', '') AS hh_package_type,
    reservation_properties.price_cents AS package_price,
    reservation_properties.revenue AS revenue,
    branches.id AS branch_id,
    branches.name AS branch_name,
    channels.name AS channel_name,
    users.email AS manager_email,
    users.username AS manager_name,
    cities.name AS city_name,
    dimension_translations.name AS dining_occasion,
    if(isNull(reservations.user_id), 'guest', 'user') AS user_type
FROM reservations
INNER JOIN restaurants
    ON reservations.restaurant_id = restaurants.id
LEFT JOIN cities
    ON restaurants.city_id = cities.id
LEFT JOIN restaurant_translations
    ON restaurants.id = restaurant_translations.restaurant_id
LEFT JOIN reservation_properties
    ON reservation_properties.reservation_id = reservations.id
LEFT JOIN branches
    ON restaurants.branch_id = branches.id
LEFT JOIN channels
    ON reservations.channel = channels.channel_id
LEFT JOIN users
    ON users.id = restaurants.user_id
LEFT JOIN dimensions
    ON dimensions.id = reservations.dining_occasion_id
LEFT JOIN dimension_translations
    ON dimension_translations.dimension_id = dimensions.id
        AND dimension_translations.locale = 'en'
WHERE restaurant_translations.locale = 'en'
  AND reservation_properties.package != ''